Feat/user bubbles
nmpereira/time-share-v2-client pull request #44
Opened 2023-06-10 04:23 UTC by nmpereira

## Description
Add user bubbles to show the list of users in the current room

Functionality:
1. When user joins, the user bubble gets added to all clients in that room
2. When user joins, the joined user gets a list of all connected clients
3. When user leaves, the user bubbles on all connected clients get updated to remove that user
4. if there are more than 6 clients, the 7th bubble is a concatenation that says +1 or +2 as required
5. Add tooltip to show the name of the user

Closes CommunityFocus/CommunityFocus/issues/61

2023-06-10 04:35 UTC, nmpereira commented on src/components/UserBubbles/MultiUserBubble.tsx
> +	// first and last character of user name
```suggestion
```

2023-06-10 04:35 UTC, nmpereira commented on src/components/UserBubbles/MultiUserBubble.tsx
> +				data-tooltip-html={users.join("<br /><br />")}
```suggestion
				data-tooltip-html={users.join("<br />")}
```

2023-06-10 04:36 UTC, nmpereira commented on src/components/UserBubbles/UserBubble.tsx
> +	// first and last character of user name
```suggestion
```

2023-06-10 04:36 UTC, nmpereira commented on src/components/UserBubbles/UserBubbles.tsx
> +			{/* if there are less than 7, show all otherwise dont render the user bubble, but show an extra bubble with the number not shown as the user */}
```suggestion
```

2023-06-10 11:11 UTC, riddlew requested changes

2023-06-10 11:11 UTC, riddlew commented on src/components/Room.tsx
> +		userList: string[];
Can we extract this to its own type to make this a little more clean?

2023-06-11 04:51 UTC, riddlew approved these changes

2023-06-11 05:01 UTC, merged