Added subtitle for work or break label
nmpereira/time-share-v2-client pull request #87
Opened 2024-01-10 22:53 UTC by sar-mko

2024-01-11 02:26 UTC, nmpereira requested changes

2024-01-11 02:26 UTC, nmpereira commented on src/components/TimerTitle/Subtitle.tsx
> +const Subtitle = (props: SubtitleProps) => {
@sar-mko please add a return type for this function

```
const Subtitle = (props: SubtitleProps) : JSX.Element => {
```

2024-01-12 05:06 UTC, sar-mko commented
I think its all fixed now!

2024-01-12 18:43 UTC, nmpereira approved these changes
🚀 Good to go! Thank you!

2024-01-12 18:43 UTC, merged